"""empty message

Revision ID: 1038dd09fd97
Revises: 2ead6bd4eab4
Create Date: 2023-01-05 14:44:54.592737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1038dd09fd97'
down_revision = '2ead6bd4eab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id', sa.String(length=24), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('profileurl', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.Column('avatarmedium', sa.String(length=200), nullable=False),
    sa.Column('avatarfull', sa.String(length=200), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_vector_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('played_game_count', sa.Integer(), nullable=False),
    sa.Column('total_playtime', sa.Integer(), nullable=False),
    sa.Column('recent_playtime', sa.Integer(), nullable=False),
    sa.Column('total_vector_bycount', sa.Text(), nullable=False),
    sa.Column('total_vector_bytime', sa.Text(), nullable=False),
    sa.Column('recent_vector_bycount', sa.Text(), nullable=False),
    sa.Column('recent_vector_bytime', sa.Text(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vector_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
