"""empty message

Revision ID: 2ead6bd4eab4
Revises: 65ae9f17ad40
Create Date: 2023-01-03 16:40:58.626227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ead6bd4eab4'
down_revision = '65ae9f17ad40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('played_game_count', sa.Integer(), nullable=False),
    sa.Column('total_playtime', sa.Integer(), nullable=False),
    sa.Column('recent_playtime', sa.Integer(), nullable=False),
    sa.Column('total_vector_bycount', sa.Text(), nullable=False),
    sa.Column('total_vector_bytime', sa.Text(), nullable=False),
    sa.Column('recent_vector_bycount', sa.Text(), nullable=False),
    sa.Column('recent_vector_bytime', sa.Text(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
