"""empty message

Revision ID: b27d48bef29e
Revises: 1ae79310ab75
Create Date: 2023-01-03 13:36:26.316662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d48bef29e'
down_revision = '1ae79310ab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('total_playtime', sa.Integer(), nullable=False),
    sa.Column('recent_playtime', sa.Integer(), nullable=False),
    sa.Column('total_vector_bycount', sa.Text(), nullable=False),
    sa.Column('total_vector_bytime', sa.Text(), nullable=False),
    sa.Column('recent_vector_bycount', sa.Text(), nullable=False),
    sa.Column('recent_vector_bytime', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
